### ISSUE TITLE
ヘッダーとフッダーの共通化

### ISSUE THREAD

**Issue by andoromeda** [CreatorsLab/CreatorsLab.github.io#12]
ページごとに個別に割り当てるのは非効率的なので共通のパーツにした方がいい

**Comment by Yosh0124** [comment]
技術は何をつかおう。
静的サイトの場合はJavascriptがいいかな。

**Comment by andoromeda** [comment]
いまちょっと調べただけのものですがこれとか使えないですかね
http://liginc.co.jp/programmer/archives/1650

**Comment by Yosh0124** [comment]
こっちも参考に。
http://webdrawer.net/other/templates.html

**Comment by andoromeda** [comment]
http://webdrawer.net/other/templates.html#c03
を参考に共通化したけどJavaScript内にガシガシHTML書くのはあまりきれいじゃないな、、、

**Comment by Yosh0124** [comment]
Trelloでなくこっちに返信します！
確かにダサいｗ
やはり動的にしなければいけないのだろうか。。。

**Comment by andoromeda** [comment]
了解です。
なんかファイル読み込みで、とか出来そうなんですが少し探してみた感じ意外とないんですよね

**Comment by Yosh0124** [comment]
結構需要ありそうな機能なのに、標準でサポートしてないんやね。

**Comment by andoromeda** [comment]
いや、検索不足かもですが、、

**Comment by andoromeda** [comment]
さすがに11年前(http://oshiete.goo.ne.jp/qa/771400.html)からは進化しているらしくそれらしい解決策がありました！
http://qiita.com/koshihikari/items/f6a90d8a19bda831d879
