### ISSUE TITLE
仮デザイン流し込み

### ISSUE THREAD

**Issue by yutakiyama** [CreatorsLab/CreatorsLab.github.io#6]
## 概要
ホワイトボードで書いたデザインを、ページに流し込みを行います。
主な作業としては差し替え・エリア作成になります。

## 変更点
- [x] header
  - [x] background
  - [x] 文章
- [x] Service
- [x] Benefits
- [ ] ご利用の流れ
  - [ ] 流れの図エリア
  - [ ] Contact Us リンク
- [ ] OUR TEAM
  - [ ] 会社概要エリア
  - [ ] メンバー
- [ ] Contact US
  - [ ] Contact Us リンク

### 関連課題
---
関連する課題があればここにリンク形式で載せる（Backlog）
 
### 親課題
---
親の課題があればここにリンク形式で載せる（Backlog）
 
#### 備考
---
別途記載する必要があれば書く

**Comment by Yosh0124** [comment]
お、サンクス！

**Comment by yutakiyama** [comment]
本格的には文章決まってから進めていくよー:poop:

**Comment by Yosh0124** [comment]
了解っす！

**Comment by andoromeda** [comment]
あ

**Comment by andoromeda** [comment]
すみません、なんかキャンセルissueというボタンを押しちゃいました

**Comment by yutakiyama** [comment]
reopenしといた！笑

**Comment by andoromeda** [comment]
お、ありがとうございます
ちょうどその方法探してました（笑

**Comment by Yosh0124** [comment]
吹いたｗ
俺も気を付けよう…(笑)

**Comment by yutakiyama** [comment]
:+1:
